DATTOBD_PACKAGE="synosnap-0.12.12.deb"
DATTOBD_VERSION="0.12.12"
AGENT_PACKAGE="Synology Active Backup for Business Agent-3.2.0-5055.deb"
AGENT_VERSION="5055"
AGENT_PACKAGE_NAME="synology-active-backup-business-linux-service"
DATTOBD_PACKAGE_NAME="synosnap"
DEBIAN_REPO="https://packages.debian.org"
UBUNTU_REPO="https://packages.ubuntu.com"
