DATTOBD_PACKAGE="synosnap-0.11.6.deb"
DATTOBD_VERSION="0.11.6"
AGENT_PACKAGE="Synology Active Backup for Business Agent-3.1.0-4968.deb"
AGENT_VERSION="4968"
AGENT_PACKAGE_NAME="synology-active-backup-business-linux-service"
DATTOBD_PACKAGE_NAME="synosnap"
DEBIAN_REPO="https://packages.debian.org"
UBUNTU_REPO="https://packages.ubuntu.com"
